window.SITE = {
  name: "Mezza",
  short: "Mezza",
  city: "General Santos City",
  region: "Soccsksargen",
  zip: "9500",
  phone: "+63835521840",
  phoneDisplay: "(083) 552 1840",
  whatsapp: "639178254300",
  whatsappDisplay: "0917 825 4300",
  email: "hello@mezza.ph",
  address: "Unit 2B, Pioneer Ave. cor. Santiago Blvd., Brgy. Dadiangas West, General Santos City 9500",
  hours: "Monday–Saturday, 8:30 AM – 5:30 PM",
  broker: "Elena Dela Peña",
  brokerTitle: "Licensed Real Estate Broker",
  prc: "REB 0021847",
  prcValid: "15 June 2027",
  ptr: "GSC-2026-44190",
  tin: "On file at the office",
  map: "https://www.openstreetmap.org/export/embed.html?bbox=125.155,6.100,125.195,6.135&layer=mapnik&marker=6.114,125.172",
  disclaimer:
    "Asking prices are indicative and may change without notice. Listings are not a public offering of a subdivision or condominium project unless a valid DHSUD License to Sell is stated. Verify title, taxes, zonal value, and physical condition independently. This website is general information, not legal, tax, or credit advice."
};

window.AREAS = [
  {
    id: "city-heights",
    name: "City Heights",
    blurb: "Gated streets, established homes, and the city's most requested family address.",
    image: "images/area-city-heights.jpg",
    goodFor: "Families who want a village setting and resale demand",
    watch: "Village rules, HOA dues, and post-June 2026 structural notes"
  },
  {
    id: "lagao",
    name: "Lagao",
    blurb: "The practical center — near SM, offices, schools, and daily errands.",
    image: "images/area-lagao.jpg",
    goodFor: "Buyers who want walkable access to malls and work",
    watch: "Traffic on the national highway and mixed-use noise"
  },
  {
    id: "san-isidro",
    name: "San Isidro",
    blurb: "Newer subdivisions and starter house-and-lots, often Pag-IBIG friendly.",
    image: "images/house-townhouse.jpg",
    goodFor: "First homes and end-user financing",
    watch: "Confirm License to Sell on developer inventory"
  },
  {
    id: "apopong",
    name: "Apopong",
    blurb: "Larger lots and more house for the peso, still inside the city.",
    image: "images/house-apopong.jpg",
    goodFor: "Buyers who want space without leaving GenSan",
    watch: "Flood pockets after heavy rain — walk the lot in weather"
  },
  {
    id: "bula",
    name: "Bula",
    blurb: "Coastal living toward Sarangani Bay, seafood, and sea breeze.",
    image: "images/area-bula.jpg",
    goodFor: "Second homes and lots with bay proximity",
    watch: "Shoreline setbacks, tide, and title against foreshore claims"
  },
  {
    id: "calumpang",
    name: "Calumpang",
    blurb: "Highway frontage and commercial strips serving the west side.",
    image: "images/lot-commercial.jpg",
    goodFor: "Retail, shop-house, and warehouse users",
    watch: "Zoning and road-right-of-way on titled plans"
  },
  {
    id: "labangal",
    name: "Labangal",
    blurb: "Close to KCC and the older west-side fabric of the city.",
    image: "images/house-labangal.jpg",
    goodFor: "In-city living without a subdivision premium",
    watch: "Tight lots and older structures after the 2026 quake"
  },
  {
    id: "tambler",
    name: "Tambler",
    blurb: "Airport road, logistics, and light industry.",
    image: "images/warehouse.jpg",
    goodFor: "Warehouses and staff housing near GES",
    watch: "Industrial neighbors and truck traffic"
  }
];

window.PROPERTIES = [
  {
    id: "city-heights-family-home",
    ref: "TS-CH-8841",
    title: "4-Bedroom Family Home in City Heights",
    intent: "sale",
    type: "house",
    barangay: "City Heights",
    address: "Blk 7 Lot 12, City Heights Subdivision, General Santos City",
    price: 8950000,
    lotSqm: 180,
    floorSqm: 220,
    beds: 4,
    baths: 3,
    parking: 2,
    yearBuilt: 2016,
    furnishing: "Semi-furnished",
    titleType: "TCT",
    titleStatus: "Clean title",
    titleNote: "Owner's duplicate TCT available for viewing at the office. No adverse annotation on the latest certified true copy.",
    whoCanBuy: "filipino",
    pagibigReady: true,
    bankAssumable: false,
    inspected2026: true,
    inspectionNote: "Walk-through completed 18 July 2026. No obvious structural failure observed. An independent civil engineer should still inspect before you buy.",
    floodNote: "Elevated village street. Seller reports no indoor flooding in the last ten years.",
    hoa: 1800,
    exclusive: true,
    featured: true,
    images: ["images/house-city-heights.jpg", "images/interior-living.jpg", "images/interior-kitchen.jpg", "images/interior-bedroom.jpg"],
    nearby: ["KCC Mall of Gensan", "Notre Dame of Dadiangas University", "General Santos City Hall"],
    lat: 6.121, lng: 125.175,
    listed: "2026-08-04",
    highlights: ["Corner-adjacent lot", "Covered two-car parking", "Service area and laundry", "Mature shade trees"],
    description: "A livable two-storey family house inside City Heights, one of GenSan's most requested village addresses. Four bedrooms, a bright living-dining volume, and a yard large enough for weekend merienda. Papers are on a Transfer Certificate of Title. This is a resale, not a developer launch.",
    legalNotes: [
      "Land ownership is limited to Filipino citizens and 60% Filipino-owned corporations (1987 Constitution, Art. XII).",
      "Buyer should obtain a certified true copy of the TCT from the Registry of Deeds of General Santos City before paying a large reservation."
    ]
  },
  {
    id: "lagao-bungalow-sm",
    ref: "TS-LG-7720",
    title: "Single-Storey House and Lot near SM Lagao",
    intent: "sale",
    type: "house",
    barangay: "Lagao",
    address: "Purok Riverside, Brgy. Lagao, General Santos City",
    price: 5480000,
    lotSqm: 150,
    floorSqm: 120,
    beds: 3,
    baths: 2,
    parking: 1,
    yearBuilt: 2012,
    furnishing: "Unfurnished",
    titleType: "TCT",
    titleStatus: "Clean title",
    titleNote: "TCT in the seller's name. Real property tax receipts for the last three years on file.",
    whoCanBuy: "filipino",
    pagibigReady: true,
    bankAssumable: false,
    inspected2026: true,
    inspectionNote: "Hairline plaster cracks only. No column or beam distress noted on visual review, August 2026.",
    floodNote: "Ask neighbors about 2022 and 2025 rain events. Lot sits slightly above the purok road.",
    hoa: 0,
    exclusive: true,
    featured: true,
    images: ["images/house-bungalow.jpg", "images/interior-living.jpg", "images/interior-kitchen.jpg"],
    nearby: ["SM City General Santos", "Lagao public market", "St. Elizabeth Hospital"],
    lat: 6.119, lng: 125.182,
    listed: "2026-08-01",
    highlights: ["One-floor living", "10–15 minutes to SM on ordinary traffic", "Room to extend at the rear"],
    description: "A practical Lagao bungalow for buyers who want mall, hospital, and school access without a village premium. Three bedrooms on one floor, a carport, and a rear yard. Ideal for a small family or an OFW who wants a lock-and-leave house.",
    legalNotes: ["Capital gains tax on a capital-asset sale is generally 6% of the higher of selling price, zonal value, or FMV."]
  },
  {
    id: "san-isidro-townhouse",
    ref: "TS-SI-6104",
    title: "Pag-IBIG-Ready Townhouse in San Isidro",
    intent: "sale",
    type: "townhouse",
    barangay: "San Isidro",
    address: "Phase 2, residential village, Brgy. San Isidro",
    price: 2150000,
    lotSqm: 72,
    floorSqm: 48,
    beds: 2,
    baths: 1,
    parking: 1,
    yearBuilt: 2023,
    furnishing: "Unfurnished",
    titleType: "TCT",
    titleStatus: "Individual title in process",
    titleNote: "Mother title still with the developer. Individual TCT targeted after full payment and documentation. Demand the License to Sell and a written turnover timeline.",
    whoCanBuy: "filipino",
    pagibigReady: true,
    bankAssumable: false,
    inspected2026: true,
    inspectionNote: "Newer construction. Cosmetic grout cracks after June 2026. No structural red flags on visual walk-through.",
    floodNote: "Village drainage is new. Confirm outfall during a rain visit.",
    hoa: 800,
    exclusive: false,
    featured: true,
    images: ["images/house-townhouse.jpg", "images/interior-bedroom.jpg", "images/interior-kitchen.jpg"],
    nearby: ["San Isidro barangay hall", "National highway", "Neighborhood chapel"],
    lat: 6.130, lng: 125.178,
    listed: "2026-07-28",
    highlights: ["Entry price under ₱2.2M", "Designed for Pag-IBIG end-user financing", "Low monthly village due"],
    description: "A compact two-bedroom townhouse for first-time buyers. Price sits inside typical Pag-IBIG low-cost brackets. This is the kind of listing where documents matter more than photos: ask for the DHSUD License to Sell, reservation agreement, and the exact title path.",
    legalNotes: [
      "PD 957: a developer cannot legally sell subdivision lots or house-and-lots to the public without a Certificate of Registration and License to Sell.",
      "Maceda Law (RA 6552) protects residential installment buyers if the contract is cancelled."
    ]
  },
  {
    id: "apopong-house-lot",
    ref: "TS-AP-5519",
    title: "Spacious House and Lot in Apopong",
    intent: "sale",
    type: "house",
    barangay: "Apopong",
    address: "National Highway interior, Brgy. Apopong",
    price: 3850000,
    lotSqm: 210,
    floorSqm: 140,
    beds: 3,
    baths: 2,
    parking: 2,
    yearBuilt: 2008,
    furnishing: "Semi-furnished",
    titleType: "TCT",
    titleStatus: "Clean title",
    titleNote: "TCT clean. One cancelled mortgage annotation already released.",
    whoCanBuy: "filipino",
    pagibigReady: true,
    bankAssumable: false,
    inspected2026: true,
    inspectionNote: "Older two-storey. Recommend a structural engineer before any second-floor renovation.",
    floodNote: "Rear yard can hold water after long rain. House floor is two steps up.",
    hoa: 0,
    exclusive: true,
    featured: false,
    images: ["images/house-apopong.jpg", "images/interior-living.jpg", "images/interior-kitchen.jpg"],
    nearby: ["Apopong barangay hall", "Public schools", "Highway jeepney route"],
    lat: 6.135, lng: 125.160,
    listed: "2026-07-22",
    highlights: ["210 sqm lot", "Fruit trees", "Room for an extension or home shop"],
    description: "More land than you usually get inside the city. Three bedrooms, a wide yard, and a straightforward TCT. Suited to a multi-generation household that wants space for a garden or a small home business.",
    legalNotes: []
  },
  {
    id: "bula-coastal-lot",
    ref: "TS-BL-4402",
    title: "300 sqm Residential Lot near the Bula Coast",
    intent: "sale",
    type: "lot",
    barangay: "Bula",
    address: "Interior road toward the coast, Brgy. Bula",
    price: 4200000,
    lotSqm: 300,
    floorSqm: 0,
    beds: 0,
    baths: 0,
    parking: 0,
    yearBuilt: null,
    furnishing: "Vacant lot",
    titleType: "TCT",
    titleStatus: "Clean title",
    titleNote: "TCT residential. Not foreshore lease. Survey plan and vicinity map available.",
    whoCanBuy: "filipino",
    pagibigReady: false,
    bankAssumable: false,
    inspected2026: false,
    inspectionNote: "Vacant land. No structure to inspect. Buyer should verify monuments and shoreline setbacks.",
    floodNote: "Coastal barangay. Check storm surge and drainage before you design a house.",
    hoa: 0,
    exclusive: true,
    featured: true,
    images: ["images/area-bula.jpg", "images/lot-residential.jpg"],
    nearby: ["Sarangani Bay", "Bula seafood strip", "City proper via coastal road"],
    lat: 6.090, lng: 125.175,
    listed: "2026-08-06",
    highlights: ["300 sqm titled lot", "Build-your-own timeline", "Sea-air neighborhood"],
    description: "A titled residential lot a short ride from the water. Enough land for a one-storey house, a small garden, and parking. We will walk the boundaries with you and flag any overlap with easements before you reserve.",
    legalNotes: [
      "The Water Code reserves easements along banks and shores. Do not assume the fence line is the titled line.",
      "Foreign buyers cannot own this land. A long-term lease is the usual alternative."
    ]
  },
  {
    id: "calumpang-commercial",
    ref: "TS-CP-9011",
    title: "Highway-Frontage Commercial Lot, Calumpang",
    intent: "sale",
    type: "commercial",
    barangay: "Calumpang",
    address: "National Highway, Brgy. Calumpang",
    price: 12800000,
    lotSqm: 450,
    floorSqm: 0,
    beds: 0,
    baths: 0,
    parking: 0,
    yearBuilt: null,
    furnishing: "Vacant commercial lot",
    titleType: "TCT",
    titleStatus: "Clean title",
    titleNote: "TCT classified commercial on the tax declaration. Confirm zoning with the City Planning Office.",
    whoCanBuy: "filipino",
    pagibigReady: false,
    bankAssumable: false,
    inspected2026: false,
    inspectionNote: "Vacant lot. Check road-right-of-way against the approved survey.",
    floodNote: "Highway grade. Ask DPWH/city engineering about future widening.",
    hoa: 0,
    exclusive: true,
    featured: true,
    images: ["images/lot-commercial.jpg", "images/area-lagao.jpg"],
    nearby: ["National Highway", "West-side retail", "Route to Polomolok"],
    lat: 6.112, lng: 125.155,
    listed: "2026-07-30",
    highlights: ["450 sqm frontage", "Retail or shop-house potential", "Titled commercial use on tax dec"],
    description: "A 450-square-meter highway lot for a buyer who already knows their use: spare parts, food, a small supermarket, or a two-storey shop-house. We will not sell this as a 'sure mall neighbor' story. We will sell the frontage, the title, and the planning constraints.",
    legalNotes: [
      "If the seller holds this as an ordinary asset, VAT and creditable withholding tax may apply instead of the 6% capital gains tax.",
      "Building permits still require city zoning clearance after you buy."
    ]
  },
  {
    id: "fatima-farm-lot",
    ref: "TS-FT-3308",
    title: "Half-Hectare Farm Lot in Fatima",
    intent: "sale",
    type: "farm",
    barangay: "Fatima",
    address: "Sitio farm road, Brgy. Fatima",
    price: 3200000,
    lotSqm: 5000,
    floorSqm: 0,
    beds: 0,
    baths: 0,
    parking: 0,
    yearBuilt: null,
    furnishing: "Agricultural land",
    titleType: "TCT",
    titleStatus: "Agricultural title",
    titleNote: "TCT is agricultural. Not yet converted. No CLOA. Buyer who wants a subdivision or non-farm use needs DAR conversion and city rezoning.",
    whoCanBuy: "filipino",
    pagibigReady: false,
    bankAssumable: false,
    inspected2026: false,
    inspectionNote: "Open land. Access is a barangay/farm road. Confirm right of way in writing.",
    floodNote: "Low spots hold water in wet months. Walk after rain.",
    hoa: 0,
    exclusive: true,
    featured: false,
    images: ["images/farm.jpg", "images/lot-hillside.jpg"],
    nearby: ["Fatima barangay roads", "Interior farms", "Route toward the city"],
    lat: 6.155, lng: 125.145,
    listed: "2026-07-12",
    highlights: ["5,000 sqm", "Agricultural TCT", "No CLOA restriction"],
    description: "A half-hectare farm parcel for agriculture, a rest house with farm use, or a long-horizon hold. We list this with a hard warning: agricultural land is not a house-and-lot. Conversion is a separate government process and is not guaranteed.",
    legalNotes: [
      "DAR land-use conversion is required before legally developing agricultural land into a non-agricultural use.",
      "CLOA and EP agrarian titles have holding periods and transfer limits. This listing is not a CLOA."
    ]
  },
  {
    id: "tambler-warehouse",
    ref: "TS-TB-2201",
    title: "Warehouse near General Santos Airport, Tambler",
    intent: "sale",
    type: "warehouse",
    barangay: "Tambler",
    address: "Airport road corridor, Brgy. Tambler",
    price: 18500000,
    lotSqm: 800,
    floorSqm: 480,
    beds: 0,
    baths: 2,
    parking: 6,
    yearBuilt: 2019,
    furnishing: "Bare warehouse",
    titleType: "TCT",
    titleStatus: "Clean title",
    titleNote: "TCT in a domestic corporation. Share transfer or asset sale can be structured. Counsel required.",
    whoCanBuy: "filipino",
    pagibigReady: false,
    bankAssumable: false,
    inspected2026: true,
    inspectionNote: "Steel frame stood the June 2026 event with minor cladding work already completed. Engineer letter on file.",
    floodNote: "Yard is concrete and graded to the drain.",
    hoa: 0,
    exclusive: true,
    featured: false,
    images: ["images/warehouse.jpg", "images/lot-commercial.jpg"],
    nearby: ["General Santos International Airport", "Makar / Tambler logistics", "Fishport corridor"],
    lat: 6.058, lng: 125.096,
    listed: "2026-08-08",
    highlights: ["800 sqm lot", "Truck yard", "Airport-side logistics"],
    description: "A working warehouse for a tuna, dry goods, or e-commerce operator who needs the airport road. Roller doors, a concrete yard, and a small office room. Corporate title — bring your lawyer to the first serious meeting.",
    legalNotes: ["A landholding corporation must remain at least 60% Filipino-owned."]
  },
  {
    id: "labangal-near-kcc",
    ref: "TS-LB-7188",
    title: "Two-Storey House near KCC, Labangal",
    intent: "sale",
    type: "house",
    barangay: "Labangal",
    address: "Interior street, Brgy. Labangal",
    price: 6750000,
    lotSqm: 160,
    floorSqm: 200,
    beds: 4,
    baths: 3,
    parking: 2,
    yearBuilt: 2010,
    furnishing: "Semi-furnished",
    titleType: "TCT",
    titleStatus: "Clean title",
    titleNote: "TCT clean. Estate documents already settled — extra court papers available.",
    whoCanBuy: "filipino",
    pagibigReady: true,
    bankAssumable: false,
    inspected2026: true,
    inspectionNote: "Non-structural cracks patched. Water tank stand was rebuilt after June 2026.",
    floodNote: "City street. Standard monsoon splash at the gate, not interior flooding.",
    hoa: 0,
    exclusive: false,
    featured: false,
    images: ["images/house-labangal.jpg", "images/interior-living.jpg", "images/interior-bedroom.jpg"],
    nearby: ["KCC Mall of Gensan", "Pioneer Avenue", "West-side schools"],
    lat: 6.112, lng: 125.168,
    listed: "2026-07-19",
    highlights: ["In-city lot", "Four bedrooms", "Near KCC and Pioneer"],
    description: "A solid family house on the Labangal side of the city, close to KCC and the Pioneer corridor. Four bedrooms on two floors. Good for a household that works in the old center and does not want a far subdivision.",
    legalNotes: []
  },
  {
    id: "katangawan-starter",
    ref: "TS-KT-5090",
    title: "Starter House and Lot in Katangawan",
    intent: "sale",
    type: "house",
    barangay: "Katangawan",
    address: "Subdivision pocket, Brgy. Katangawan",
    price: 2890000,
    lotSqm: 100,
    floorSqm: 80,
    beds: 3,
    baths: 2,
    parking: 1,
    yearBuilt: 2021,
    furnishing: "Unfurnished",
    titleType: "TCT",
    titleStatus: "Clean title",
    titleNote: "Individual TCT already issued in the seller's name.",
    whoCanBuy: "filipino",
    pagibigReady: true,
    bankAssumable: false,
    inspected2026: true,
    inspectionNote: "Light partition cracks only. House is post-2019 construction.",
    floodNote: "Confirm drainage along the circumferential road after heavy rain.",
    hoa: 600,
    exclusive: false,
    featured: false,
    images: ["images/house-bungalow.jpg", "images/house-townhouse.jpg"],
    nearby: ["Circumferential road", "Growing east-side retail", "City proper"],
    lat: 6.145, lng: 125.195,
    listed: "2026-08-02",
    highlights: ["Under ₱3M", "Individual title already out", "Three bedrooms"],
    description: "A straightforward starter house for a young family or an OFW sending home a first property. Title is already individual — that is the point of this listing.",
    legalNotes: []
  },
  {
    id: "dadiangas-mixed-use",
    ref: "TS-DW-9904",
    title: "Three-Storey Mixed-Use on Dadiangas West",
    intent: "sale",
    type: "commercial",
    barangay: "Dadiangas West",
    address: "Near Pioneer Avenue, Brgy. Dadiangas West",
    price: 15900000,
    lotSqm: 200,
    floorSqm: 420,
    beds: 4,
    baths: 4,
    parking: 2,
    yearBuilt: 2014,
    furnishing: "Ground floor bare, upper floors residential",
    titleType: "TCT",
    titleStatus: "Clean title",
    titleNote: "TCT clean. Business permits historically issued for ground-floor retail.",
    whoCanBuy: "filipino",
    pagibigReady: false,
    bankAssumable: false,
    inspected2026: true,
    inspectionNote: "Engineer review recommended for the third floor. Ground-floor columns appear sound. Report can be commissioned.",
    floodNote: "City street drainage. Occasional curb splash.",
    hoa: 0,
    exclusive: true,
    featured: true,
    images: ["images/mixed-use.jpg", "images/interior-living.jpg", "images/office.jpg"],
    nearby: ["Pioneer Avenue", "Santiago Boulevard", "Downtown services"],
    lat: 6.114, lng: 125.171,
    listed: "2026-08-10",
    highlights: ["Shop below, home above", "200 sqm city lot", "Walk to Pioneer"],
    description: "A three-storey mixed-use building a short walk from Pioneer. Ground floor can take a clinic, shop, or office. Upper floors work as the owner's house or staff rooms. After June 2026 we treat every mid-rise walk-up as a document-and-engineer sale.",
    legalNotes: ["Building occupancy and fire-safety certificates should be updated after the 2026 earthquake before you reopen a public-facing ground floor."]
  },
  {
    id: "conel-view-lot",
    ref: "TS-CN-1180",
    title: "Hillside View Lot in Conel",
    intent: "sale",
    type: "lot",
    barangay: "Conel",
    address: "Upper road, Brgy. Conel",
    price: 1680000,
    lotSqm: 240,
    floorSqm: 0,
    beds: 0,
    baths: 0,
    parking: 0,
    yearBuilt: null,
    furnishing: "Vacant lot",
    titleType: "TCT",
    titleStatus: "Clean title",
    titleNote: "TCT residential. Slope and access should be checked by a geodetic engineer.",
    whoCanBuy: "filipino",
    pagibigReady: false,
    bankAssumable: false,
    inspected2026: false,
    inspectionNote: "Hillside land. Buyer should assess slope stability and access after the 2026 earthquake.",
    floodNote: "Elevated. Drainage is downslope — design your cut and fill carefully.",
    hoa: 0,
    exclusive: false,
    featured: false,
    images: ["images/lot-hillside.jpg", "images/farm.jpg"],
    nearby: ["Conel upland roads", "City view", "Interior farms"],
    lat: 6.175, lng: 125.185,
    listed: "2026-07-08",
    highlights: ["240 sqm", "View lot", "Quiet upland barangay"],
    description: "A hillside lot for a buyer who wants air and a view more than mall adjacency. Come at dusk, then come again after rain. We will not oversell the access road.",
    legalNotes: []
  },
  {
    id: "city-heights-vacant-lot",
    ref: "TS-CH-2255",
    title: "252 sqm Vacant Lot inside City Heights",
    intent: "sale",
    type: "lot",
    barangay: "City Heights",
    address: "Interior village street, City Heights",
    price: 4500000,
    lotSqm: 252,
    floorSqm: 0,
    beds: 0,
    baths: 0,
    parking: 0,
    yearBuilt: null,
    furnishing: "Vacant lot",
    titleType: "TCT",
    titleStatus: "Clean title",
    titleNote: "TCT clean. Village construction guidelines apply.",
    whoCanBuy: "filipino",
    pagibigReady: false,
    bankAssumable: false,
    inspected2026: false,
    inspectionNote: "Cleared lot. Check setbacks in the village building rules before you design.",
    floodNote: "Village street, well graded.",
    hoa: 1200,
    exclusive: true,
    featured: false,
    images: ["images/lot-residential.jpg", "images/area-city-heights.jpg"],
    nearby: ["Village park", "City Heights gates", "West-side malls"],
    lat: 6.122, lng: 125.176,
    listed: "2026-07-25",
    highlights: ["Inside an established village", "Build to your plan", "Neighboring homes already built"],
    description: "Vacant land inside City Heights is scarce. 252 square meters is enough for a generous one-storey or a compact two-storey with a garden. Village rules will shape the house more than the city code will.",
    legalNotes: ["HOA and deed-of-restrictions can limit height, fence, and use even if the city would allow more."]
  },
  {
    id: "san-isidro-duplex",
    ref: "TS-SI-8044",
    title: "Brand-New Duplex in San Isidro",
    intent: "sale",
    type: "duplex",
    barangay: "San Isidro",
    address: "New pocket development, Brgy. San Isidro",
    price: 4980000,
    lotSqm: 110,
    floorSqm: 130,
    beds: 3,
    baths: 3,
    parking: 2,
    yearBuilt: 2025,
    furnishing: "Bare",
    titleType: "TCT",
    titleStatus: "Title path disclosed",
    titleNote: "Sold as one duplex building on one lot. Individual split is not yet done. Ask for the License to Sell if this is still developer inventory.",
    whoCanBuy: "filipino",
    pagibigReady: true,
    bankAssumable: false,
    inspected2026: true,
    inspectionNote: "Completed 2025. No quake damage of note. Turnover punch list still open on paint.",
    floodNote: "New drainage. Visit during rain.",
    hoa: 900,
    exclusive: false,
    featured: true,
    images: ["images/house-duplex.jpg", "images/interior-kitchen.jpg", "images/interior-bedroom.jpg"],
    nearby: ["San Isidro schools", "Highway access", "Newer villages"],
    lat: 6.128, lng: 125.181,
    listed: "2026-08-11",
    highlights: ["Live in one side, rent the other", "New build", "Three bedrooms per plan"],
    description: "A new duplex for a household that wants rental help on the monthly. Live in one side and let the other. Financing is realistic for Pag-IBIG or a bank if income and title path line up.",
    legalNotes: ["If marketed by a developer, PD 957 requires a License to Sell before reservation money is collected."]
  },
  {
    id: "lagao-rent-3br",
    ref: "TS-LG-R12",
    title: "3-Bedroom House for Rent in Lagao",
    intent: "rent",
    type: "house",
    barangay: "Lagao",
    address: "Quiet interior street, Brgy. Lagao",
    price: 25000,
    lotSqm: 140,
    floorSqm: 110,
    beds: 3,
    baths: 2,
    parking: 1,
    yearBuilt: 2011,
    furnishing: "Semi-furnished",
    titleType: "TCT",
    titleStatus: "Owner-occupied title",
    titleNote: "Lease only. Owner holds TCT. Standard one-year contract, two months deposit, one month advance.",
    whoCanBuy: "anyone",
    pagibigReady: false,
    bankAssumable: false,
    inspected2026: true,
    inspectionNote: "Habitable. Minor plaster repair done after June 2026.",
    floodNote: "No interior flooding reported.",
    hoa: 0,
    exclusive: true,
    featured: true,
    images: ["images/house-bungalow.jpg", "images/interior-living.jpg", "images/interior-bedroom.jpg"],
    nearby: ["SM City General Santos", "Offices along the highway", "Hospitals"],
    lat: 6.118, lng: 125.180,
    listed: "2026-08-09",
    highlights: ["₱25,000 / month", "Semi-furnished", "One parking"],
    description: "A clean three-bedroom rental for a professional household or a small family. Near the Lagao commercial spine. Foreign tenants can lease even though they cannot buy the land.",
    legalNotes: ["A lease does not transfer ownership. Foreign nationals may lease land and buildings under Philippine law, subject to contract terms."]
  },
  {
    id: "city-heights-rent-4br",
    ref: "TS-CH-R07",
    title: "4-Bedroom Village House for Rent, City Heights",
    intent: "rent",
    type: "house",
    barangay: "City Heights",
    address: "City Heights Subdivision",
    price: 35000,
    lotSqm: 170,
    floorSqm: 190,
    beds: 4,
    baths: 3,
    parking: 2,
    yearBuilt: 2015,
    furnishing: "Semi-furnished",
    titleType: "TCT",
    titleStatus: "Owner holds title",
    titleNote: "Lease. Village HOA must approve long-stay tenants per house rules.",
    whoCanBuy: "anyone",
    pagibigReady: false,
    bankAssumable: false,
    inspected2026: true,
    inspectionNote: "Cleared for occupancy after a July 2026 walk-through.",
    floodNote: "None noted.",
    hoa: 1800,
    exclusive: true,
    featured: false,
    images: ["images/house-city-heights.jpg", "images/interior-living.jpg", "images/interior-kitchen.jpg"],
    nearby: ["Village amenities", "KCC Mall", "Schools"],
    lat: 6.120, lng: 125.174,
    listed: "2026-08-03",
    highlights: ["Village security", "Four bedrooms", "Two-car parking"],
    description: "A larger City Heights rental for a family that wants gates, neighbors, and a yard. HOA rules apply. Pets by written approval.",
    legalNotes: []
  }
];

window.BARANGAYS = [
  "Apopong", "Bula", "Calumpang", "City Heights", "Conel",
  "Dadiangas West", "Fatima", "Katangawan", "Labangal", "Lagao",
  "San Isidro", "Tambler"
];
